### ISSUE TITLE
Build a new box

### ISSUE THREAD

**Issue by NotfatPrince** [coloradocube/balloonsat#15]
# Description

See if Randy's box fits our payload. If it does not, build a new one from Styrofoam.

# Knowledge

1. RPi 4 B [mechanical drawing](https://datasheets.raspberrypi.com/rpi4/raspberry-pi-4-mechanical-drawing.pdf).

# Dependent
1. Volume #13

**Comment by ivogeorg** [comment]
# Sketches of v2

| Description | Sketch |
| --- | --- |
| Overall structure |  <img src="https://user-images.githubusercontent.com/6043344/140579423-fa2f9d7f-0be7-4c85-ab26-7422cd380a22.png" width="300" /> | 
| Framed board stack |  <img src="https://user-images.githubusercontent.com/6043344/140579700-044a6128-d55f-42f4-bfa0-33d369a6b091.png" width="300" /> |
| 4-camera multiplexor |  <img src="https://user-images.githubusercontent.com/6043344/140579909-5f474256-c1de-4b90-8c22-c54e4492ad32.png" width="300" /> |
| Rope tube fitting |  <img src="https://user-images.githubusercontent.com/6043344/140580001-4d779b11-7dd9-40e1-bb15-cafc086c6ad9.png" width="300" /> |

**Comment by ivogeorg** [comment]
![image](https://user-images.githubusercontent.com/6043344/141537231-76acc41a-5cc2-404e-8a40-27fd2aae88f5.png)

**Comment by ivogeorg** [comment]
@DannyS10 This is how the RPi and UPS have to be situated:
![image](https://user-images.githubusercontent.com/6043344/144507065-a6664d9b-7351-4b74-b0ab-2739487fd9dc.png)  
or  
![image](https://user-images.githubusercontent.com/6043344/144507123-3c9b6e0e-fea1-4c84-af00-45b215ce1155.png)
