### ISSUE TITLE
Functional battery power system

### ISSUE THREAD

**Issue by ivogeorg** [coloradocube/balloonsat#17]
# Description

Power a RPI 4 with the EP-0136 UPS PLUS. Load the processor with continuous video capture and storage to SD card. Time the discharge.

# Open questions

1. How can the RPi gracefully power itself down upon UPS low-battery condition?
2. Can the UPS communicate with the RPi?

# Knowledge

1. [EP-0136](https://wiki.52pi.com/index.php/EP-0136) on the 52pi wiki.
2. UPS Plus [repo](https://github.com/geeekpi/upsplus) on Github.

**Comment by dperry29** [comment]
11/4/2021 Update

Battery Type:
  -Need to decide what battery type we will actually fly
  -Will run room temp battery discharge comparison bench tests 11/5/21

Power delivery system:
  -Raspberry Pi UPS, X728 V2.1 to be ordered and (if comes in) tested next week
  -Will do full evaluation tomorrow on powerboost 1000c (still think we can use this if we setup it up correctly)
  -possibly continue to troubleshoot EP-0316

**Comment by dperry29** [comment]
Sounds like @sschis (seth) got the new battery board running a pi with no crashes. Nice work!

**Comment by ivogeorg** [comment]
@sschis @dtucker18 

Yesterday you guys said the new power pack HAT doesn't measure and report the current like the EP-0136. Couldn't we use the [ZIO voltage and current sensor](https://www.smart-prototyping.com/blog/Zio-Current-and-Voltage-Sensor-Qwiic-Start-Guide) we bought for that? Max current rating is 3.2 A and nominal RPi 4 max current is 3 A. There seems to even be an [RPi library](https://www.hackster.io/chrisb2/raspberry-pi-ina219-voltage-current-sensor-library-f3bb54) for it.

**Comment by dperry29** [comment]
Ya that was the plan! try that thing out

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Ivo Georgiev ***@***.***>
Sent: Friday, November 12, 2021 9:44:27 AM
To: MSUSAT/balloonsat ***@***.***>
Cc: Perry, Daniel ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [MSUSAT/balloonsat] Functional battery power system (Issue #17)


NOTICE: This email originated from outside the University. Please exercise caution when replying or opening links and attachments.


@sschis<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsschis&data=04%7C01%7Cdperry29%40msudenver.edu%7Cabb9ff5d38a748d0c8b908d9a5fbb13b%7C03309ca417334af9a73cf18cc841325c%7C1%7C0%7C637723322726151385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tm%2BtcoJ6a%2FUma7jYGsVm1Z67aMifl4rZuPEn9svmty8%3D&reserved=0> @dtucker18<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdtucker18&data=04%7C01%7Cdperry29%40msudenver.edu%7Cabb9ff5d38a748d0c8b908d9a5fbb13b%7C03309ca417334af9a73cf18cc841325c%7C1%7C0%7C637723322726161382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=I3U8%2FJrwSs2%2BzhuNFs9ivjxkm%2BiUTWfe1o%2FuAm%2Bduek%3D&reserved=0>

Yesterday you guys said the new power pack HAT doesn't measure and report the current like the EP-0136. Couldn't we use the ZIO voltage and current sensor<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.smart-prototyping.com%2Fblog%2FZio-Current-and-Voltage-Sensor-Qwiic-Start-Guide&data=04%7C01%7Cdperry29%40msudenver.edu%7Cabb9ff5d38a748d0c8b908d9a5fbb13b%7C03309ca417334af9a73cf18cc841325c%7C1%7C0%7C637723322726171376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6PWB9a5KfY2s%2FO4ng3zBsALjgDB%2BB9zaNlAJh1lisV0%3D&reserved=0> we bought for that? Max current rating is 3.2 A and nominal RPi 4 max current is 3 A. There seems to even be an RPi library<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.hackster.io%2Fchrisb2%2Fraspberry-pi-ina219-voltage-current-sensor-library-f3bb54&data=04%7C01%7Cdperry29%40msudenver.edu%7Cabb9ff5d38a748d0c8b908d9a5fbb13b%7C03309ca417334af9a73cf18cc841325c%7C1%7C0%7C637723322726181370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lt1pre7y0IU5PAZIvRUfzIZcG%2Bz5C%2BVNBZ1wioE0qGQ%3D&reserved=0> for it.

**Comment by ivogeorg** [comment]
# Update

We are no longer using the 52pi UPS Plus EP-0136. We are using the [Geekworm X728](https://geekworm.com/collections/raspberry-pi-ups/products/raspberry-pi-x728-max-5-1v-8a-18650-ups-power-management-board).

**Comment by sschis** [comment]
I suppose we can use it to test the current draw on the bench test and use that as rough assumptions for flight use, but not sure how it would fit into the stack long-term.

**Comment by dperry29** [comment]
Update 11/12/2021

INA-219 operational and giving sensor data
X728 Powering Rpi 3 via cabling (not in stack)

Next Steps:
Physical integration. 
  -Which pins are used/unused on X728 and INA-219
  -How will the pins be connected to the flight Rpi
  -Building custom cable setup
*All of this is currently functional but we need to make physically compatible with the rest of the stack setup and "flight-worthy"

**Comment by sschis** [comment]
option 1:
separated stack
ribbon cable(female plug) from power board
splice out the two 5V pins into current sensor (V+)
splice two 5V pins (V-) from current sensor back into ribbon cable
ribbon cable into TOP HAT (need a new hat..old one not working? Qwiic PiHat v10)
	^^need a 40pin female to long male extender so the ribbon cable can plug into top of stack
	(regular existing male pins too short to connect hat AND ribbon cable female plug)

parts needed:
	40pin ribbon cable: shorturl.at/xFJR7
	new PiHat Qwiic v10: https://www.sparkfun.com/products/14459

**Comment by ivogeorg** [comment]
PSU works fine with 2 batteries for about 1.5 hours at 75% load (stress test) and over 2.5 hours with normal load (~10%). This was tested at lawn demo and will be sufficient for EOSS-319 in Jan 2022.
