### ISSUE TITLE
Integrate UPS sensors into sensorium code

### ISSUE THREAD

**Issue by dperry29** [coloradocube/balloonsat#23]
# Description

UPS readings are part of critical telemetry (See #3)

1. Battery/UPS readings come in two forms:
   1. Internal UPS sensors (voltage, capacity, etc.)
   2. External discrete voltage and current sensor.
2. Both types are available over I2C.

# Knowledge
1. UPS: https://geekworm.com/collections/raspberry-pi-ups/products/raspberry-pi-x728-max-5-1v-8a-18650-ups-power-management-board
2. Voltage and current sensor: https://www.sparkfun.com/products/15176

# Deliverables
1. Determine all the data points that are available.
2. Determine the ranges, along the safe/normal operating range, and danger zones.
3. Write a Python package to expose polling functionality to the telemetry application. (See #3)

**Comment by ivogeorg** [comment]
Depends on #17

**Comment by ivogeorg** [comment]
![image](https://user-images.githubusercontent.com/6043344/142458393-3dbb0af8-da1c-4d14-b9d5-244991140b80.png)

**Comment by ivogeorg** [comment]
PSU sample code is straight I2C read: capacity (in %) and battery voltage (in V), with critical values for shutoff.
Zio Qwiic sensor is read using the Blinka libraries: voltage and current.
