### ISSUE TITLE
Capture still images with quad camarray

### ISSUE THREAD

**Issue by ivogeorg** [coloradocube/balloonsat#54]
# Description

Configure color quad [camarray](https://www.arducam.com/camarray-release-multiple-mipi-camera-solution/). It mimics a single camera but with 4x the width of the normal camera. Images are composite of the views of the 4 cameras. Requires a driver compiled for the current kernel.

# Knowledge

1. Arducam [product page](https://www.uctronics.com/arducam-1mp-4-quadrascopic-camera-bundle-kit-for-raspberry-pi-nvidia-jetson-nano-xavier-nx.html).
2. Documentation [page](https://www.arducam.com/docs/arducam-obisp-mipi-camera-module/).
3. Github [drivers and source](https://github.com/ArduCAM/Arducam_OBISP_MIPI_Camera_Module).
4. YouTube [video](https://www.youtube.com/watch?v=MlRbOJ9n3Q4).
5. Software & hardware [guide](https://www.arducam.com/docs/cameras-for-raspberry-pi/synchronized-stereo-camera-hat/camarray-arducam-1mp-ov9782-color-quad-camera-bundle-kit/).

**Comment by Christopher-Dauchter** [comment]
The driver issue can likely be fixed by updating the kernel driver using their (Arducam) makefile .

https://github.com/ArduCAM/Arducam_OBISP_MIPI_Camera_Module/tree/master/sourceCode/5.4.51

**Comment by ivogeorg** [comment]
Requires building own driver for current RPi kernel.
