### ISSUE TITLE
Record video with quad camarray

### ISSUE THREAD

**Issue by ivogeorg** [coloradocube/balloonsat#55]
# Knowledge

1. Quad-camera bundle [hardware & software guide](https://www.arducam.com/docs/cameras-for-raspberry-pi/synchronized-stereo-camera-hat/camarray-arducam-1mp-ov9782-color-quad-camera-bundle-kit/).
2.

**Comment by Christopher-Dauchter** [comment]
The driver issue can likely be fixed by updating the drivers using their (Arducam) makefile. 

https://github.com/ArduCAM/Arducam_OBISP_MIPI_Camera_Module/tree/master/sourceCode/5.4.51
