### ISSUE TITLE
Iridium SBD communication for sending telemetry over a RockBLOCK module

### ISSUE THREAD

**Issue by ivogeorg** [coloradocube/balloonsat#6]
# Description

The primary ground communications channel for the balloonsat is the Iridium satellite constellation through the RockBLOCK short-burst-data messaging modules. Since the packet size is 340 downlink and 270 uplink, this channel is only good for telemetry and control (insofar a balloonsat can be controlled). With clear sky, a message can be sent about every **10 seconds**.

We have two versions of the RockBLOCK:
1. The [9602 or v2](https://www.sparkfun.com/products/13745)
2. The [9603 or v3](https://www.sparkfun.com/products/14498), which is preferred due to lower weight and other improvements.

The PRi will connect to the RockBLOCK with a USB cable. V2 requires an external USB-to-Serial chip. V3 might have that internally.
 
Use RockBLOCK short burst messages to deliver live telemetry. In particular:
1. Connect to RPi and get the RockBlock library running
2. Write program to Schedule and queue messages per type and subsystem
3. Set up the msusat.org website and a Web service to show the telemetry.
4. Set up redirect to the Web service at msusat.org 

# Knowledge

1. [9603 vendor product page, specs, and docs](https://www.groundcontrol.com/product/rockblock-9603-compact-plug-play-satellite-transmitter/)
2. [RockBlock guide](https://docs.rockblock.rock7.com/docs). In particular:
   1. [What's RockBLOCK](https://docs.rockblock.rock7.com/docs).
   2. [Integration with application](https://docs.rockblock.rock7.com/docs/integration-with-application)
   3. [Short burst data](https://docs.rockblock.rock7.com/docs/about-short-burst-data-sbd).
   4. [Receiving data](https://docs.rockblock.rock7.com/docs/receive-data).
   5. [RockBLOCK data cycle](https://docs.rockblock.rock7.com/docs/the-rockblock-data-cycle).
   6. [Data compression](https://docs.rockblock.rock7.com/docs/compressing-your-data).
3. [RockBLOCK API reference](https://docs.rockblock.rock7.com/reference/testinput). In particular:
   1. [Sending MT messages](https://docs.rockblock.rock7.com/reference/testinput#receiving-mo-messages-via-http-webhook). MT messages are ground/web service to RockBLOCK.
4. [FTDI USB-to-Serial drivers](https://ftdichip.com/drivers/)
5. [Simple message tutorial](http://makersnake.com/rockblock/) (**DOES NOT WORK**)
6. SparkFun [video demo](https://www.youtube.com/watch?v=NOJ_VtSikAA&t=171s) for connection from laptop.
7. [Adafruit](https://www.adafruit.com/) and [CircuitPython](https://circuitpython.org/) ([On Wikipedia](https://en.wikipedia.org/wiki/CircuitPython)):
   1. 9603 [product page](https://www.adafruit.com/product/4521) and [user guide](https://learn.adafruit.com/using-the-rockblock-iridium-modem?view=all).
   2. Adafruit CircuitPython RockBLOCK library/driver on [Github](https://github.com/adafruit/Adafruit_CircuitPython_RockBlock) and [ReadTheDocs](https://circuitpython.readthedocs.io/projects/rockblock/en/latest/).
   3. [Raspberry Pi example with RockBLOCK and driver](https://learn.adafruit.com/using-the-rockblock-iridium-modem/raspberry-pi-example).
   4. CircuitPython [releases](https://github.com/adafruit/circuitpython/releases) and [libraries](https://circuitpython.org/libraries).
   5. The Adafruit library depends on Adafruit-Blinka ([PyPi](https://pypi.org/project/Adafruit-Blinka/) and [Github](https://github.com/adafruit/Adafruit_Blinka)).
8. [iridium AT Command Reference](https://cdn.sparkfun.com/datasheets/Wireless/General/IRDM_ISU_ATCommandReferenceMAN0009_Rev2.0_ATCOMM_Oct2012.pdf).

# Deliverables 

1. A driver library for the RockBLOCK in the form of a Python package. Managed by the Flight Executive (See #28).
2. Minimal functions:
   1. Send periodic telemetry (See #3).
   2. Accept and send asynchronous critical alerts.
   3. Priority message queue.
   4. Check for incoming messages (aka check mailbox). _The incoming (MT) messages have to be retrieved by the RockBLOCK. TODO: Is there a PUSH mechanism that can be configured?_
   5. Check and report status of Iridium connection.
 3. Acceptance tests:
    1. Check RPi-RockBLOCK connection (indoors). (AT --> OK)
    2. Round trip to ground with UPS and voltage and current sensor data (outdoors, on ground).
    3. Periodic telemetry after power up from inside battery-powered enclosure (outdoors, on ground).
    4. Periodic telemetry after power up from inside battery-powered enclosure (outdoors, in the air).

**Comment by ivogeorg** [comment]
# USB to Serial converters
1. SparkFun [FT231X Breakout](https://www.sparkfun.com/products/13263) (**BOB-13263**):
   1. Defaults to 5 V (needs jumper soldering).
   2. No headers.
   3. USB, Micro B.
2. SparkFun [FTDI Basic Breakout - 5V](https://www.sparkfun.com/products/9716) (DEV-09716):
   1. Defaults to 5 V (needs jumper soldering).
   2. USB, Mini B.

**Comment by NotfatPrince** [comment]
# Description
1. Get the RockBlock library running
2.  Schedule and queue messages per type and subsystem
3. Pack and encrypt data (encrypted text should be in ASCII) MSUSAT/Systems#2 
# Knowledge
[RockBlock guide](https://docs.rockblock.rock7.com/docs)
[Drivers](https://ftdichip.com/drivers/)
[Simple message tutorial](http://makersnake.com/rockblock/)

# Deliverables 
For Indoor lab test of the system
- The RockBlock should communicate with the the RPi (We won't be able to send messages from indoors)
- The RockBlock should receive data packages from RPi and send an acknowledgement that data has been received 

For outdoor lab test of the system. No box.
- The RockBlock should be able to send scheduled messages with data from the sensorium and internal telemetry.

**Comment by ivogeorg** [comment]
# Sending a message AT commands

AT
_OK_
AT&KO
_OK_
AT+SBDWT=Message to send
_OK_
AT+SBDIX
_+SBDIS: 0, 4, 0, 0, 0, 0_ (upon successful transmission)
_+SBDIS: 32, 4, 2, 0, 0, 0_ (upon failed transmission)
OK_

**Comment by ivogeorg** [comment]
![image](https://user-images.githubusercontent.com/6043344/140590665-e00ed62b-88a5-4dc7-aa3c-1d2e199a4672.png)

**Comment by ahmedjazeera11** [comment]
"Connect to RPi and get the RockBlock library running" issue solved

**Comment by ahmedjazeera11** [comment]
DSD TECH 2PCS USB to TTL Serial Adapter with CP2102 Chip Compatible with Windows 7,8,10,Linux,Mac OS X 
https://www.amazon.com/gp/product/B078W5L8W1/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1

**Comment by ivogeorg** [comment]
## Iridium application

![image](https://user-images.githubusercontent.com/6043344/142505279-19f5bf45-d4d0-4d4c-bd70-e8758917f0a6.png)

**Comment by ivogeorg** [comment]
## Critical alerts from flight executive

![image](https://user-images.githubusercontent.com/6043344/142505728-bd792eb3-49c2-453c-bea3-f8337a1902b2.png)

**Comment by ivogeorg** [comment]
@nmead1 Read through this issue and let's discuss. This will feel like drinking from the hose, but don't worry. Tomorrow, I can give you a RockBLOCK to play with.

**Comment by ivogeorg** [comment]
The RPi setup for using the UART for the RockBLOCK specifies to _enable_ **Serial** but _disable_ **Serial Console**. In reference to #30, could both be enabled?

**Comment by ivogeorg** [comment]
The `rockblock_simpletest.py` works with Serial on and the following code:
```python
import serial
uart = serial.Serial("/dev/serial0", 19200)
```
Temperature fell under 0 degrees Celsius and could not run the `rockblock_sendtext.py` and `rockblock_senddata.py`.
