### ISSUE TITLE
FE v0.3.6 - Stream video from RPi WiFi hotspot

### ISSUE THREAD

**Issue by ivogeorg** [coloradocube/balloonsat#63]
# Knowledge

1. [Web interface for RPi camera](https://elinux.org/RPi-Cam-Web-Interface).
2. [RPi WiFi access point setup](https://github.com/coloradocube/balloonsat/blob/main/wifi/Access_Point_Setup.sh).

**Comment by NotfatPrince** [comment]
[streaming data with wifi](https://raspberrypi.stackexchange.com/questions/95840/how-to-create-local-hotspot-on-raspberry-pi-3b-to-share-files-on-android)
